// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  'ErrorPage': {
    'home': 'Back to home',
    'title': 'Oops, something went wrong!',
    'try': 'Try again'
  },
  'Manifest': {
    'name': 'Ultra Mobile Blog'
  },
  'Header': {
    'title': 'Hello World'
  },
  'Footer': {
    'copyright': 'Copyright'
  }
};
export default messages;